ignore:
  - "src/server/server.js"
  - "src/index.js"
  - "src/views/arena-main.js"
  - "src/views/arena-team.js"
  - "src/views/arena-leaderboard.js"
  - "src/views/login.js"
  - "src/views/player-portal-home.js"
  - "src/views/admin-home.js"